use serde::{Deserialize, Serialize};
use ts_rs::{Config, TS};

pub const PROTOCOL_VERSION: &str = "1.0";

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "snake_case")]
pub enum HealthStatus {
    Ready,
    NotConfigured,
    Unavailable,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
pub struct SystemHealthRequest {
    pub client_protocol_version: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
pub struct SystemHealthResponse {
    pub protocol_version: String,
    pub core: HealthStatus,
    pub storage: HealthStatus,
    pub providers: HealthStatus,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CommandErrorCode {
    ProtocolMismatch,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, TS)]
pub struct CommandError {
    pub code: CommandErrorCode,
    pub message_key: String,
}

impl CommandError {
    #[must_use]
    pub fn protocol_mismatch() -> Self {
        Self {
            code: CommandErrorCode::ProtocolMismatch,
            message_key: "errors.protocolMismatch".to_owned(),
        }
    }
}

#[must_use]
pub fn generated_typescript() -> String {
    let config = Config::default();
    let declarations = [
        HealthStatus::decl(&config),
        SystemHealthRequest::decl(&config),
        SystemHealthResponse::decl(&config),
        CommandErrorCode::decl(&config),
        CommandError::decl(&config),
    ]
    .map(|declaration| format!("export {declaration}"))
    .join("\n\n");

    format!(
        "// @generated by flit-protocol. Do not edit.\n\
         export const PROTOCOL_VERSION = \"{PROTOCOL_VERSION}\" as const;\n\n\
         {declarations}\n"
    )
}
